### ISSUE TITLE
Device not working / responding, error messages in log

### ISSUE THREAD

**Issue by thehvoort** [lynxcs/homebridge-ct200#2] opened 2021-08-21 14:33 UTC
Hello!

First of all - thank you for creating this. We've just got a new heating system installed, and this really came in handy.

Apparently though, i am not able to set up the plugin correctly. After installing & setting up the config as described, i am getting the device in homekit, although its not responding.

Also, i am getting the following message in my log:

```
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Current Heating Cooling State' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Target Heating Cooling State' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Target Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Temperature Display Units' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.
[21.8.2021, 16:20:43] [homebridge-ct200] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
```

After some time, my console is getting "spammed" with the following:

```
[21.8.2021, 16:24:17] [CT200] Encountered error during GET: /zones/zn1/status
[21.8.2021, 16:24:17] [CT200] Error: MAX_RETRIES_REACHED
    at /usr/lib/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15
```

Are there any obvious configuration issues that might trigger this?

Thanks in advance!

**Comment by lynxcs** [comment] 2021-08-21 20:18
The "plugin slows down Homebridge" is due to the fact that the bosch api is queried for each request. The speed at which this completes depends on internet speed / distance to their server / device performance. If the response isn't fast enough, homebridge complains. Nevertheless, this should be fixed by an upcoming release, which will use homebridge commands that don't wait for the read handler. I'll implement this when I get around to rewriting the code in typescript and switch to registering a platform.

The worrisome error is the second one. So far I've identified that it happens in two cases. Either you 1) filled out the config wrong (access key, serial and password (which must be no longer than 8 characters!)) 2) The bosch-xmpp library bugs out after a while on lower-powered devices (I might be wrong though, I'm not sure of the exact cause yet)

Easiest way to determine if it's the former is to install bosch-xmpp (sudo npm install -g bosch-xmpp) and try to use the client with any endpoint (e.g bosch-xmpp easycontrol --serial=$SERIAL --access-key=$ACCESS --password=$PASS get /zones/list). If it returns any errors that means the info you provided was wrong. I'm 99% sure that it's this one, due to it not responding even when you restart homebridge.

If it's the second option, I honestly have no idea how to correct it. This might be fixed when i rewrite it in typescript, we'll see. It could be that I programmed it wrong, my javascript skills are poor.

If you don't know how to interpret the output of the bosch-xmpp command, paste it here and I'll have a look.

**Comment by thehvoort** [comment] 2021-08-22 21:59
Thanks for the quick help.

This is the response i got:
https://i.imgur.com/OyYByHx.png

Regarding the usage: If i remove the spaces of the serial & access key, it's telling me those are "missing".
This might be a pretty dumb issue on my side, so please excuse any "dumb" questions that might result.

Edit: 
Adding my config here as well, just for reference.

https://i.imgur.com/2xOlfne.png

**Comment by lynxcs** [comment] 2021-08-22 22:10
Hello, I believe I see the issue. When entering the serial and access key, it should be as one word with no spaces (e.g "1234567"). Slight oversight on my part as I didn't specify this, but the $ shouldn't be there (as it just means a variable in bash, my bad). The other thing you could try is to put "" around the serial, access key and password. Please try these fixes and see if the command works now.

Edit: The command should look something like this:
`bosch-xmpp easycontrol --serial="SERIAL" --access-key="ACCESS" --password="PASS" get /zones/list`

**Comment by thehvoort** [comment] 2021-08-22 22:33
Hey,
when entering the command, the console "freezes", or rather: i dont get any response.

Is the CT200 API open by default, or do i need to change some settings in the app beforehand? It seems like homebridge can't reach the CT200.

(it is connected to the right network, and i can ping it from the homebridge console as well.)

**Comment by lynxcs** [comment] 2021-08-23 08:38
The CT200 API is open by default as far as I know, because I didn't need to change anything inside the app.

The command "freezing" while it's waiting for a response is normal, if it's no longer than ~ 5 seconds. Any longer than that and you have a problem. This is also the reason the accessory doesn't respond for you.

Could you run `telnet 139.15.227.114 5222` and check if you can connect to it? If it says "connected to ...." then at least the service is reachable for you and the issue is something else.

Edit:
Please also check if you can control the thermostat from the official app (easycontrol). If it's unreachable there then that's the problem

**Comment by lynxcs** [comment] 2021-09-08 19:06
This issue could be in part due to the bosch changing the API url, which explains the bosch-xmpp command freezing. Should be fixed with current release.

EDIT: "This plugin slows down homebridge" error messages should also be gone.

**Closed as completed by lynxcs** 2021-09-08 19:06 UTC
