### ISSUE TITLE
Issue with ct200

### ISSUE THREAD

**Issue by Arrbe** [lynxcs/homebridge-ct200#28] opened 2022-03-05 08:59 UTC
**Describe The Bug:**
Plug-in loaded, registered but doesn’t work. No issues with login or passed. Below the logs.

**Logs:**

[homebridge-ct200] Error: MAX_RETRIES_REACHED
    at /usr/local/lib/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)

**Plugin Config:**
{
    "access": "fsdfsfdsfgdsgsdgs",
    "serial": "xxxxxx",
    "password": "xxxxxxxxx",
    "away": false,
    "zoneInterval": 2,
    "auxInterval": 5,
    "zones": [
        {
            "index": 1,
            "name": "Thermostat"
        }
    ],
    "_bridge": {
        "username": "xx:….xx",
        "port": 38865
    },
    "platform": "CT200"
}

**Environment:**

* **Plugin Version**: v2.2.5
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.4.0
* **NPM Version**: 8.3.1
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by dan3o3** [comment] 2022-03-07 13:26
I can tell the same on my setup:

`[3/7/2022, 2:13:15 PM] [CT200] Error: MAX_RETRIES_REACHED
    at /homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)`

The CT200 unit is brand new (FW 01.04.00, Hardware-Version 10), usual bosch mobile app works fine.

Environment:

- Plugin Version: v2.2.6
- Homebridge Version: 1.4.0
- Node.js Version: 16.14.0
- NPM Version: 8.3.1

**Comment by lynxcs** [comment] 2022-03-07 14:41
Hi,
If you are still encountering this issue, please try running this command: `bosch-xmpp easycontrol --serial="SERIAL" --access-key="ACCESS" --password="PASSWORD" get /zones/list`
If this command successfully returns a list of zones, then we can rule out that the issue is something with your config (if you don't have this command, you can install with `sudo npm install -g bosch-xmpp`).

**Comment by dan3o3** [comment] 2022-03-07 15:18
Tried that command but the result is the same error as in the logs above.

**Comment by lynxcs** [comment] 2022-03-07 15:46
I'm not quite sure I understand, could you post the output after running that command?

**Comment by Arrbe** [comment] 2022-03-07 16:36
Tried the command too after installing Bosch-xmpp. The same error as in the homebridge log: “Error: MAX_RETRIES_REACHED…..” I also tried with a wrong serial, access, and password and instead I got a message of “authentication failure”. This means that the issue is not related to the config but with the way the server communicates with our xmpp clients (i.e. get /zones/list doesn’t work)

**Comment by dan3o3** [comment] 2022-03-07 18:22
> I'm not quite sure I understand, could you post the output after running that command?

As Arrbe wrote, the error is the same as from the log I posted.
Did Bosch change something on their side? Wonder if there are CT200 users which actually can use the plugin.

**Comment by lynxcs** [comment] 2022-03-07 19:26
Could be something with firmware version (if you both don't have at least CT200 v03.06.02 then that would explain it). Otherwise, I have no idea. I think it's either something related to login details or CT200 version. As for the plugin, I haven't had any issues so far, so it's probably not Bosch changing something.

**Comment by dan3o3** [comment] 2022-03-07 19:40
Probably that's indeed a firmware issue, the magic question is how to update it? I heard the devices will update on their own but until today there was no change in the version.

**Comment by Arrbe** [comment] 2022-03-07 19:44
Yes, I have v03.02.00 which is newer than dan3o3's but older than that. What would be the improvement? How to update? I tried from the app and from the CT200 display but it seems that there are no updates. Maybe is it due to the localization? I saw that Alexa and IFTTT are supported in Germany only.
https://github.com/geckse/node-bosch-easy-control-wrapper uses different APIs, doesn't it?
This is the reference that I used https://www.programmableweb.com/api/bosch-thermotechnology-device-rest-api-v10

**Comment by lynxcs** [comment] 2022-03-07 19:59
In your case, the issue is because of old version. Since v03.06.02 bosch changed endpoint (which was updated in bosch-xmpp). If you want to try to use the plugin without updating CT200 check this issue #26.

**Comment by Arrbe** [comment] 2022-03-07 20:34
Yes, thanks a lot. I would prefer to get a solution to update the firmware. Otherwise, I read your solution of using XMPP 1.2.0 with the latest plugin version. I sent a question in issue #26 to get mine forced as well.

**Comment by dan3o3** [comment] 2022-03-07 21:26
I can confirm that the solution with plugin downgrade works. Unfortunately you cannot update the firmware on your own and according to that other thread Bosch seems to have closed down the update server until at least April.
Only error left is this, probably ignoreable until my unit got its update:
`[3/7/2022, 10:25:11 PM] [CT200] Error: HTTP_NOT_FOUND
    at /homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:213:25
    at tryCatcher (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)`

**Comment by Arrbe** [comment] 2022-03-08 00:59
Unfortunately the solution is not working for me. Xmpp1.2.0 works but with bosch-xmpp easycontrol --serial=SERIAL --access-key=ACCESS --password=PASSWORD get /zones/list, I mean removing quotation marks “”.
Instead the plugin does not update i.e. the Home icon shows the default class values: temp 0 and set point 10. I tried removing the quotation marks for example in the SERIAL of the JSON since it is defined as a number in the src but nothing happens.

**Comment by lynxcs** [comment] 2022-03-08 08:36
HTTP_NOT_FOUND doesn't look like something that should be ignoreable 😅

Are you sure you changed the bosch-xmpp version correctly? (Since there was a lot of unrelated things in the issue I linked, I'll repeat the steps below):

1. Make sure you have the latest version of homebridge-ct200
2. Go to directory where homebridge-ct200 was installed
3. Run `sudo npm install bosch-xmpp@1.2.0` (important: be in homebridge-ct200 directory and without `-g` flag!!!)
4. Restart homebridge

Let me know how that goes (or if you already followed these steps)

Though it could also be that this error is due to older endpoint / some other incompatibility.

EDIT: Following the previous issue, it seems that for MarkRoks homebridge-ct200 v2.1.2 was most stable with bosch-xmpp@1.2.0

**Comment by dan3o3** [comment] 2022-03-08 10:07
This is exactly what I did, also the device is available and shows the same counters as the Bosch App, that's why I thought the error is "cosmetic"... ;)

![image](https://user-images.githubusercontent.com/25102490/157215471-28bdb559-12f1-434c-990a-fd17fab748f9.png)

**Comment by Arrbe** [comment] 2022-03-08 21:52
I got the unit substituted and magically it was @ v3.8.1. Thus after changing the password 3 times and reinstalling all finally everything works fine now. Thanks a lot to all.

**Comment by lynxcs** [comment] 2022-03-09 16:05
Great to hear. Closing.

**Closed as completed by lynxcs** 2022-03-09 16:05 UTC
Labels: bug
